spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:

  h2.console.enabled: true

logging:
  level:
    root: info
#    org.springframework.web: DEBUG
    ru.bstrdn.voting: debug
