spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
    h2.console.enabled: true


server:
  port: 8080